# LAB 1 Ishaan Mehta EB02 E18CSE069

In [14]:
import numpy as np

In [19]:
a=np.array([[1,2,3],[4,5,6]])
print("Array of integers:\n",a)
b=np.array([[1,2,3],[4,5,6]], dtype='float')
print("Array of float:\n", b)
c=np.array([[1+4.j,2],[5,6]],dtype='complex')
print("Array of complex numbers:\n",c)

Array of integers:
 [[1 2 3]
 [4 5 6]]
Array of float:
 [[1. 2. 3.]
 [4. 5. 6.]]
Array of complex numbers:
 [[1.+4.j 2.+0.j]
 [5.+0.j 6.+0.j]]


In [32]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])
print("Sum of arrays:\n",a+b)
print("Transpose of array:\n",a.T)
print("Elementwise multiplication:\n",a*b)
print("Dot Product:\n",a.dot(b))
print("Element at index (2,0):\n",a[2,0])

Sum of arrays:
 [[11 13 15]
 [17 19 21]
 [23 25 27]]
Transpose of array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Elementwise multiplication:
 [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
Dot Product:
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]
Element at index (2,0):
 7


In [37]:
print("First two rows and last two columns",a[:2,-2:])
print("Reverse using slicing:\n",a[::-1,::-1])
print("Reverse using flip:\n",np.flip(a))

First two rows and last two columns [[2 3]
 [5 6]]
Reverse using slicing:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Reverse using flip:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [7]:
!pip install wget

  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9686 sha256=5e0f03708edf86fa437a14486d0c13b8f72a9ce4a3cc5377033a583f915516a6
  Stored in directory: c:\users\ishaan\appdata\local\pip\cache\wheels\a1\b6\7c\0e63e34eb06634181c63adacca38b79ff8f35c37e3c13e3c02
Successfully built wget
100% [..................................................................................] 473 / 473

'Desktop'

In [12]:
#download csv files from url
import wget
filename=wget.download("https://raw.githubusercontent.com/DeepConnectAI/challenge-week-1/master/data/structured_data/data.csv")
filename

100% [..................................................................................] 473 / 473

'data.csv'

In [18]:
#storing into numpy array(without using pandas)
from numpy import genfromtxt
mydata = genfromtxt('data.csv', delimiter=',',dtype=None)
mydata

C:\Users\Ishaan\anaconda3\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  This is separate from the ipykernel package so we can avoid doing imports until


array([[b'Country', b'Age', b'Salary', b'Purchased',
        b'Price Category Of Purchase'],
       [b'France', b'44', b'72000', b'No', b'1'],
       [b'Spain', b'27', b'48000', b'Yes', b'1'],
       [b'Germany', b'30', b'54000', b'No', b'2'],
       [b'Spain', b'38', b'61000', b'No', b'3'],
       [b'Germany', b'40', b'', b'Yes', b'1'],
       [b'France', b'35', b'58000', b'Yes', b'2'],
       [b'Spain', b'', b'52000', b'No', b'3'],
       [b'France', b'48', b'79000', b'Yes', b'1'],
       [b'Germany', b'50', b'83000', b'No', b'2'],
       [b'France', b'37', b'67000', b'Yes', b'2'],
       [b'France', b'18', b'54400', b'No', b'3'],
       [b'Germany', b'22', b'55000', b'Yes', b'3'],
       [b'Germany', b'', b'58800', b'Yes', b'1'],
       [b'France', b'28', b'42000', b'No', b'3'],
       [b'France', b'24', b'41000', b'No', b'2'],
       [b'Germany', b'35', b'69000', b'No', b'1'],
       [b'Germany', b'32', b'67000', b'Yes', b'3'],
       [b'Germany', b'38', b'65000', b'Yes', b'3'],
  