### Ishaan Mehta  E18CSE069 EB02 LabWeek1_Question1

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [5]:
#subtask1 - read file
data=pd.read_csv("data.csv")
pd.set_option('display.max_columns', None)
print(data)

    Country   Age   Salary Purchased  Price Category Of Purchase
0    France  44.0  72000.0        No                           1
1     Spain  27.0  48000.0       Yes                           1
2   Germany  30.0  54000.0        No                           2
3     Spain  38.0  61000.0        No                           3
4   Germany  40.0      NaN       Yes                           1
5    France  35.0  58000.0       Yes                           2
6     Spain   NaN  52000.0        No                           3
7    France  48.0  79000.0       Yes                           1
8   Germany  50.0  83000.0        No                           2
9    France  37.0  67000.0       Yes                           2
10   France  18.0  54400.0        No                           3
11  Germany  22.0  55000.0       Yes                           3
12  Germany   NaN  58800.0       Yes                           1
13   France  28.0  42000.0        No                           3
14   France  24.0  41000.

In [9]:
#subtask2- numerical and categorical
numerical=data.select_dtypes(include=[np.number])
categorical=data.select_dtypes(exclude=[np.number])
#category of purchase should be moved to categorical (it goes into numerical since it has integers as data)
categorical.insert(2,'Price Category Of Purchase',numerical['Price Category Of Purchase'])
del numerical['Price Category Of Purchase']
#displaying column names
print(numerical.columns)
print(categorical.columns)

Index(['Age', 'Salary'], dtype='object')
Index(['Country', 'Purchased', 'Price Category Of Purchase'], dtype='object')


In [13]:
#subtask3 - handle missing values
numerical_handled=numerical.fillna(numerical.mean())
print(numerical_handled.head(10),"\n\n")
print(categorical.head(10))

         Age        Salary
0  44.000000  72000.000000
1  27.000000  48000.000000
2  30.000000  54000.000000
3  38.000000  61000.000000
4  40.000000  60364.705882
5  35.000000  58000.000000
6  34.222222  52000.000000
7  48.000000  79000.000000
8  50.000000  83000.000000
9  37.000000  67000.000000 


   Country Purchased  Price Category Of Purchase
0   France        No                           1
1    Spain       Yes                           1
2  Germany        No                           2
3    Spain        No                           3
4  Germany       Yes                           1
5   France       Yes                           2
6    Spain        No                           3
7   France       Yes                           1
8  Germany        No                           2
9   France       Yes                           2


In [14]:
#subtask4 - OneHotEncode the categorical data
encoder=OneHotEncoder(categories='auto')
encoded_array= encoder.fit_transform(categorical[['Country','Purchased']]).toarray()
print(encoded_array)

[[1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0.]
 [1. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0.]]


In [17]:
#subtask5 - Normalize
numerical_normalized=((numerical_handled-numerical_handled.min())/(numerical_handled.max()-numerical_handled.min()))*20
print(numerical_normalized)

          Age     Salary
0   16.250000  14.761905
1    5.625000   3.333333
2    7.500000   6.190476
3   12.500000   9.523810
4   13.750000   9.221289
5   10.625000   8.095238
6   10.138889   5.238095
7   18.750000  18.095238
8   20.000000  20.000000
9   11.875000  12.380952
10   0.000000   6.380952
11   2.500000   6.666667
12  10.138889   8.476190
13   6.250000   0.476190
14   3.750000   0.000000
15  10.625000  13.333333
16   8.750000  12.380952
17  12.500000  11.428571
18  16.875000   9.221289
19   4.375000   9.221289
