### Ishaan Mehta E18CSE069 EB02 LabWeek4

In [52]:
import numpy as np

In [53]:
iter = 8
matrixSize = 3**iter

In [54]:
m = []

In [55]:
apl=np.zeros((10,1))
dia=np.zeros((10,1))

In [56]:
for j in range(10):
    matr=np.zeros((matrixSize, matrixSize),dtype=np.bool)
    matr[0][1] = 1
    matr[0][2] = 1
    matr[1][0] = 1
    matr[2][0] = 1
    p=(j/10)+0.05
    for n_iter in range(2,iter):
        step = 3**(n_iter-1)
        for x in range(step):
            for y in range(step):
                    matr[x+step][y+step] = matr[x][y]
                    matr[x+2*step][y+2*step] = matr[x][y]
        for i in range(step, 2*step):
            if np.random.rand()<=p:
                matr[0][i] = matr[step][i]
                matr[i][0] = matr[i][step]
            if np.random.rand()<=p:
                matr[0][i+step] = matr[step][i]
                matr[i+step][0] = matr[i][step]
    m.append(matr)

In [57]:
matr=np.array(m)

In [58]:
matr.shape

(10, 6561, 6561)

In [59]:
matr

array([[[False,  True,  True, ..., False, False, False],
        [ True, False, False, ..., False, False, False],
        [ True, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False,  True,  True, ..., False, False, False],
        [ True, False, False, ..., False, False, False],
        [ True, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False,  True,  True, ..., False, False, False],
        [ True, False, False, ..., False, False, False],
        [ True, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, Fal

In [60]:
import networkx as nx

In [61]:
for i in range (len(matr)):
    a=nx.Graph(matr[i])
    l=list(nx.connected_components(a))
    s=0
    for j in l:
        # print(i)
        s= max(s, nx.diameter(a.subgraph(j)))
    dia[i,0]=s

In [62]:
dia

array([[ 4.],
       [12.],
       [22.],
       [22.],
       [20.],
       [14.],
       [14.],
       [10.],
       [ 8.],
       [ 8.]])

In [ ]:
for i in range (len(matr)):
    a=nx.Graph(matr[i])
    l=list(nx.all_pairs_shortest_path_length(a))
    s=0
    for j in l:
        print(i,j[0])
        s=s+sum(j[1].values())
    apl[i,0]=s
    apl

In [41]:
apl=apl*2/21520080
print(apl)

[[0.00054201]
 [0.01346315]
 [0.00148104]
 [0.67654321]
 [3.14905149]
 [2.99403794]
 [2.52303523]
 [2.64769648]
 [1.97452575]
 [1.35284553]]


In [69]:
nb=[]
for i in range (len(matr)):
    a=nx.Graph(matr[i])
    nb.append(nx.betweenness_centrality(a))

In [71]:
nb[5]

{0: 0.08794201834029396,
 1: 0.0,
 2: 0.0,
 3: 2.3241199022754064e-08,
 4: 5.075877866569489e-05,
 5: 5.075877866569489e-05,
 6: 0.00010156403972943528,
 7: 0.0,
 8: 0.00020303511466277955,
 9: 0.00017798884918259159,
 10: 9.280210769784962e-05,
 11: 0.0,
 12: 2.533290693480194e-05,
 13: 1.0845892877285229e-07,
 14: 0.0002195208718362562,
 15: 0.00010156403972943531,
 16: 0.0,
 17: 0.000295837222360619,
 18: 0.0004734542123588698,
 19: 0.0002868428783388464,
 20: 0.0,
 21: 3.376946218006017e-05,
 22: 0.00042197495652345136,
 23: 1.3170012779560638e-07,
 24: 0.00010156403972943528,
 25: 0.0,
 26: 0.00020303511466277955,
 27: 0.0003707345107799463,
 28: 0.0,
 29: 0.0,
 30: 1.549413268183604e-08,
 31: 0.00012785315599545701,
 32: 0.00012785315599545701,
 33: 0.00010156403972943526,
 34: 0.0,
 35: 0.00028012949199253086,
 36: 0.00019465617612737562,
 37: 5.599650753024077e-07,
 38: 0.0,
 39: 3.371959253655823e-05,
 40: 9.683832926147526e-08,
 41: 0.00035949153134993105,
 42: 0.000101564039

In [72]:
eb=[]
for i in range (len(matr)):
    a=nx.Graph(matr[i])
    eb.append(nx.edge_betweenness_centrality(a))

In [74]:
eb[5]

{(0, 1): 0.00010157954803141998,
 (0, 2): 0.00010157954803141998,
 (0, 4): 0.00015225315147527336,
 (0, 5): 0.00015225315147527336,
 (0, 8): 0.0003044598347218041,
 (0, 10): 0.00019409004675324744,
 (0, 14): 0.00032064626773380296,
 (0, 17): 0.00039658309820407285,
 (0, 19): 0.00038800196529631463,
 (0, 22): 0.0005229457015649458,
 (0, 31): 0.00022822162459653231,
 (0, 32): 0.00022822162459653231,
 (0, 35): 0.0003793413938450446,
 (0, 41): 0.00045867066858620224,
 (0, 44): 0.0005257874336242247,
 (0, 49): 0.0008962859658349932,
 (0, 55): 0.0006609439494028665,
 (0, 56): 0.0006609439494028665,
 (0, 76): 0.0013887556799665993,
 (0, 82): 0.000417618862259893,
 (0, 85): 0.0005258542678190125,
 (0, 89): 0.0006151058556835191,
 (0, 112): 0.0006635914757685103,
 (0, 116): 0.0007553584610380313,
 (0, 122): 0.0009922883546351856,
 (0, 130): 0.0012670580250870765,
 (0, 136): 0.0013585148126618977,
 (0, 137): 0.0013585148126618977,
 (0, 164): 0.0003613768205196472,
 (0, 166): 0.000410756514290171